import React from 'react'

export default function GeneralFields(props) {
  return (
    <div>
      <input
        type="text"
        name="title"
        value={props.formData.title}
        onChange={props.handleChange}
        placeholder="title"
      />
      <input
        type="text"
        name="date_production"
        value={props.formData.date_production}
        onChange={props.handleChange}
        placeholder="date_production"
      />
      <input
        type="text"
        name="productors"
        value={props.formData.productors}
        onChange={props.handleChange}
        placeholder="productors"
      />
      <input
        type="text"
        name="nbr_invoice"
        value={props.formData.nbr_invoice}
        onChange={props.handleChange}
        placeholder="nbr_invoice"
      />
      <input
        type="text"
        name="nbr_contract"
        value={props.formData.nbr_contract}
        onChange={props.handleChange}
        placeholder="nbr_contract"
      />
      <input
        type="text"
        name="type_support"
        value={props.formData.type_support}
        onChange={props.handleChange}
        placeholder="type_support"
      />
      <input
        type="text"
        name="nbr_support"
        value={props.formData.nbr_support}
        onChange={props.handleChange}
        placeholder="nbr_support"
      />
      <input
        type="text"
        name="tech_comments"
        value={props.formData.tech_comments}
        onChange={props.handleChange}
        placeholder="tech_comments"
      />
      <input
        type="text"
        name="quality"
        value={props.formData.quality}
        onChange={props.handleChange}
        placeholder="quality"
      />
      <input
        type="text"
        name="language"
        value={props.formData.language}
        onChange={props.handleChange}
        placeholder="language"
      />
      <input
        type="text"
        name="frequency"
        value={props.formData.frequency}
        onChange={props.handleChange}
        placeholder="frequency"
      />
      <input
        type="text"
        name="format"
        value={props.formData.format}
        onChange={props.handleChange}
        placeholder="format"
      />
      <textarea
        name="synopsis"
        value={props.formData.synopsis}
        onChange={props.handleChange}
        placeholder="synopsis"
      />
      <input
        type="text"
        name="version"
        value={props.formData.version}
        onChange={props.handleChange}
        placeholder="version"
      />
      <input
        type="text"
        name="event_location"
        value={props.formData.event_location}
        onChange={props.handleChange}
        placeholder="event_location"
      />
      <input
        type="text"
        name="event_date"
        value={props.formData.event_date}
        onChange={props.handleChange}
        placeholder="event_date"
      />
      <input
        type="text"
        name="sequence"
        value={props.formData.sequence}
        onChange={props.handleChange}
        placeholder="sequence"
      />
      <input
        type="text"
        name="genres"
        value={props.formData.genres}
        onChange={props.handleChange}
        placeholder="genres"
      />
    </div>
  )
}
